### PR TITLE
Add support for PuppetDB v4 API.

### LINKED ISSUE #4: Add support for self-signed certificates and puppetdb v4 + report_time over catalog_time
Can you make this work for Nagios and puppet v4? i've changed to script to fit my needs, would rather see it properly maintaned here.

To get around the https communication on a self-signed puppetdb certificate, i added
$ua->ssl_opts( verify_hostname => 0 ,SSL_verify_mode => 0x00);

I've change the timestamp used to identify the health of an agent from catalog_timestamp to report_timestamp. This gives me an indication if the agent dropped off the line or not.
(Basically search-replace catalog_timestamp > report_timestamp)

Finally i've changeed the endpoints to match the v4 API rather that v3
my $uri = URI->new( $url . '/api/pdb/query/v4/nodes' );
my $uri = URI->new( $url . 'v4/event-counts' );

See file here: https://gist.github.com/kasperbrandenburg/f538ecd0367ce44bf499

### PR DESCRIPTION
**Pull request by robinelfrink**
Based on kasperbrandenburg's gist. Closes #4.

### CODE REVIEW

**Comment by evgeni** [comment]
Hi,

thanks! Totally forgot about that Puppet 4 thing :)

I'd like you to do one small change before merging, though. Could you implement it in a more general way so we can even add v5 at some point? My initial idea was to have a hash "apiurls" with something like the following structure:

    apiurls = {
       3 => { 'nodes' => 'v3/nodes', 'event-counts' => 'v3/event-counts' },
       4 => {  … }
    }

and then the functions just have to know the api version and can pull the right url from that hash.

What do you think?

**Comment by evgeni** [comment]
Oh, and your commit message misses a "Closes #4" ;-)

**Comment by robinelfrink** [comment]
Modified, squashed and updated.

**Comment by evgeni** [comment]
Awesome
Thanks

**Pull request merged**
